language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install pytest
script: py.test
env:
- SETTINGS=config.TestConfig
deploy:
  provider: heroku
  api_key:
    secure: VkgK6jY8SOHplhXbNew7pHd1mScFBvnbSy8VdkhBv+FeBAVyXkvXteMlT95gVOSVgftYQnwH6QYwL9/qIsXAnaN6JRVswv9NvV0eOvpqe8rfznU/MOKOqvFumHcTt4AhtVLB0YCixJVcdcrzX/hWF6YUNUMhYb0CO/+lrgPUS+I=
  app: lr-property-frontend
  on:
    repo: LandRegistry/property-frontend
