language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt
- pip install python-coveralls
env:
  global:
  - secure: oJJRU5sc/UE+9dFdnGL16k/NsnEFluxS3qAYsTuyZpcAcdwjwou2ccx3waC1PDD3WMPgsQD51+1ZhFSgqJ0noHy5LNg3leayDoxY76es5YzWpPzWGFaPPJwZqYxSTcZjcCJne+TK1hpMRc/InLng/u6wLWQY7ZFYfpzoFwv4Ldc=
  - SETTINGS='config.TestConfig'
script:
- source ./environment.sh
- source ./environment_test.sh
- py.test --cov propertyfrontend  tests/ --cov-report=term --cov-report=html
after_success:
- coveralls --ignore-errors
deploy:
  provider: heroku
  api_key:
    secure: QeHgbE86S+pEyDheTSjY+FAZtYh4LAbDY9bETbzfajg+ttNRUSnEgNYWH3Awi4jWsOJ2em4FMp6n70GqeDq9wUoCFZNesZFVEjjyhL8nJbnrdBvnc7p7LRO9SQWmfb+Ab9yOtT+bilUcyzr2AaEt5P1ES1wbzTQALfKrwxlnKqU=
  app: lr-property-frontend
  on:
    repo: LandRegistry/property-frontend
