language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
- pip install -r requirements_test.txt 
- pip install python-coveralls 
env:
- SETTINGS=config.TestConfig
script: py.test --cov propertyfrontend  tests/ --cov-report=term --cov-report=html
after_success:
  - coveralls --ignore-errors
deploy:
  provider: heroku
  api_key:
    secure: TMpwzEww7Nr4+mSXakB8JUQFI5Uw3hGHLp6gaT7CQKKfDgThSYSOQIDydgzXTJKV3PrpToW4LlllEGlPCgWnUkB9McCmE6zrxJf5V2VQ2FmG5JpFuYlyI4iP4IAR0woZ0ucKRMzofpI9Nq1F+WLgl2aBNHAOGUna6MZ3bMvrQBY=
  app: lr-property-frontend
  on:
    repo: LandRegistry/property-frontend
